### ISSUE TITLE
Installation Error : nodes table can not be populated  

### ISSUE THREAD

**Issue by cparsania** [spodell/Darkhorse2#4]
Hi, Following is the error message during installation. Nodes table can not be populated 
`DBD::mysql::db do failed: Incorrect integer value: '' for column 'comments' at row 1 at load_taxonomy_nodes.pl line 192, <INPUT> line`

**Comment by cparsania** [comment]
Worked fine after changing data type of 'comments' column in the node table. 

Changed the script `load_taxonomy_nodes.pl` line number 116 , `comments` data type` varchar(100)` from` int(11)`

**Comment by spodell** [comment]
Thanks - added this fix to latest release (DarkHorse-2.0_rev08).
