### ISSUE TITLE
Error in installing Darkhorse tool

### ISSUE THREAD

**Issue by subarna-slg** [spodell/Darkhorse2#7]
I am trying to install Darkhorse tool ( version DarkHorse-2.0_rev08) for HGT calculations. When I am running the script 
./install_darkhorse2.pl -c config_filename, I am getting the following error :

"ERROR: Creation of file $input_directory/nr_all_ids.tab unsuccessful\n"

Please provide some suggestions

**Comment by spodell** [comment]
Need to change shebang line from /use/local/bin/perl to /usr/bin/perl in final script called by install.pl ?

I am currently out of country on vacation without computer. Will fix when I return home (June 2018). Sorry for the delay. 
 
- Sheila
