### ISSUE TITLE
Error in using Darkhorse tool ( version DarkHorse-2.0_rev08)

### ISSUE THREAD

**Issue by ethan-mfy** [spodell/Darkhorse2#9]
I am trying to use Darkhorse tool  ( version DarkHorse-2.0_rev08) for HGT calculations. When I am running the script

darkhorse2.pl -c config_template -t XXX.m8 -e exclude_list_template -g pep.fa  -f 0.2 

The errors is as follows :
"  BLAST INPUT ERROR.
  Couldn't find match id "XP_014100720.1" in database DarkHorse_final
001	XP_014100720.1	23.5	438	276	14	105	502	4	422	7.3e-14	87.0 "

Please provide some suggestions.  Thank you very much.

**Comment by spodell** [comment]
Problem is mismatch between database and blast search file. Check to be sure that installation of DarkHorse database was completely successful (check that sizes of MySQL tables described in installation log file closely match number of lines serving as as input for those tables). Also check to be sure the blast search was done versus the "informative_sequences.faa" file generated by the installer.
